### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by sonisourabh** [colmbrady/lottie-reactxp#21] opened 2020-03-05 10:33 UTC
Getting above mentioned error on android. Can you rectify or advice.

**Comment by colmb** [comment] 2020-03-05 19:03
Its hard to say with the lack of information you provided, e.g. the code your using, version of React XP, and the full stack trace of the error, but at a guess you are trying to access window.document in a React Native (XP) app and that object does not exist?? It's only available on Web in the DOM.

Ill try to help if you can give me better info.

**Comment by sonisourabh** [comment] 2020-03-07 00:09
Thanks for your reply and giving me few pointers. I have just tried a toy program as described in the README file and got this error on android (works fine on web though). Refer the exception stack in the attached image.
![Screenshot_20200305-160306](https://user-images.githubusercontent.com/59862118/76131802-f3eab580-6035-11ea-8acd-a54a878ceb65.png)

**Comment by sonisourabh** [comment] 2020-03-07 07:16
Following are dependencies in package.json
  "dependencies": {
    "lottie-reactxp": "^1.1.1",
    "react": "16.13.0",
    "react-dom": "16.13.0",
    "react-native": "0.59.10",
    "react-native-windows": "0.59.0-rc.3",
    "reactxp": "2.0.0",
    "reactxp-imagesvg": "^2.0.0",
    "reactxp-navigation": "^2.0.0"
}
Saw following warning on yarn install:
[3/4] Linking dependencies...
warning " > lottie-reactxp@1.1.1" has incorrect peer dependency "react-native-windows@^0.33.0".
warning " > lottie-reactxp@1.1.1" has incorrect peer dependency "react-native@^0.51.0".
warning " > lottie-reactxp@1.1.1" has incorrect peer dependency "reactxp@^0.46.3".

**Comment by colmb** [comment] 2020-03-08 20:16
The stacktrace shows that you loading ReactDOM on your native project so its never going to work as ReactDOM can only run in a browser - look at the ReactXP getting started guide for help - https://microsoft.github.io/reactxp/docs/using-reactxp.html

The warnings you are getting R.E peerDependencies are likely not the cause of the issue. Perhaps the jump from ReactXP to 2.0 may have some incompatibilities but I would think not.

Without seeing your code, I cant really help any further, but I would think your native project is loading your web app entry point, not the native entry.

**Comment by colmbrady** [comment] 2020-05-04 21:42
Im closing this issue due to non-response. Please reopen if you have more info.

**Closed as completed by colmbrady** 2020-05-04 21:42 UTC
